//! XSD codegen driver (ADR-0008).
//!
//! Produces the typed definition structs in `crates/tg-defs/src/generated.rs`
//! from `schema/workload.xsd`.
//!
//! The result is **checked in**, not produced at every build: the delivery
//! crates' build stays free of the codegen toolchain (ADR-0023), and schema
//! changes become visible in the diff. `codegen --check` in CI breaks when
//! generated code and XSD diverge — exactly the "silent schema drift" ADR-0008
//! wants to exclude.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use xsd_parser::config::OptimizerFlags;
use xsd_parser::{Config, IdentType};

use crate::TaskError;

const SCHEMA: &str = "schema/workload.xsd";
const TARGET: &str = "crates/tg-defs/src/generated.rs";
const NS_PREFIX: &[u8] = b"tg";
const NS_URI: &[u8] = b"urn:tardigrade:workload:v1";
const ROOT_ELEMENT: &str = "tg:workloads";

/// Header of the generated file.
///
/// The lint exceptions deliberately apply only to this module: generated code
/// does not satisfy `missing_docs` and `clippy::pedantic` and shall not.
/// `unsafe` stays forbidden via the crate root (invariant 2).
const HEADER: &str = "\
// @generated by `cargo xtask codegen` from schema/workload.xsd — do not edit by hand.
//
// Regenerate:  cargo xtask codegen
// Check:       cargo xtask codegen --check
//
// The XSD's facets (pattern, minLength/maxLength, minInclusive/
// maxInclusive) take effect in the newtypes below as validate_str/validate_value
// and are enforced on deserialization.
//
// The line below names the version of the schema from which this file arose. A
// test in `tg-defs` recomputes it — so a drift between XSD and generated code
// stands out in the Definition of Done and not only in `cargo xtask ci`.

#![allow(missing_docs)]
#![allow(unreachable_pub)]
#![allow(unused)]
#![allow(clippy::all)]
#![allow(clippy::pedantic)]
// The regex literals below come from the XSD's facets and are compile-time
// constants; `Regex::new` can only fail on them if the codegen produced a broken
// pattern. The crate root forbids panic-capable calls on the production path,
// so the reason stands here.
#![allow(clippy::unwrap_used)]
#![allow(clippy::unreachable)]
";

/// How the version line in the generated file's header begins.
///
/// It stands **also** in `tg-defs`, because the test there looks for the same
/// line. Two places for one string — the alternative would be a dependency of
/// `tg-defs` on `xtask`, i.e. a layering inversion. The test fails if they
/// diverge.
const SCHEMA_MARKER: &str = "Schema version:";

/// The schema's version, as a number over its bytes.
///
/// **A written-out FNV-1a and not `DefaultHasher`**, for the same reason as in
/// `tg_model::keys` (ADR-0057): that one's result is expressly not stable
/// between Rust versions, and a version number that shifts on a compiler update
/// would report a drift that does not exist. It has to achieve nothing
/// cryptographically.
fn schema_digest(root: &Path) -> Result<u64, TaskError> {
    let schema = fs::read(root.join(SCHEMA))?;

    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in &schema {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }

    Ok(hash)
}

/// Produces the Rust code from the XSD.
fn render(root: &Path) -> Result<String, TaskError> {
    let mut config = Config::default()
        .with_schema(root.join(SCHEMA))
        .with_namespace(NS_PREFIX, NS_URI)
        .with_quick_xml()
        .with_derive(["Debug", "Clone", "PartialEq"])
        .with_generate([(IdentType::Element, ROOT_ELEMENT)]);

    // Decisive for ADR-0008: without this `remove` the optimizer flattens
    // restricted simple types onto their base type (WorkloadName -> String) and
    // throws all facets away. Pattern and value ranges would then be pure
    // documentation and the validation would fail silently.
    config
        .optimizer
        .flags
        .remove(OptimizerFlags::USE_UNRESTRICTED_BASE_TYPE_SIMPLE);

    let code = xsd_parser::generate(config).map_err(|err| TaskError::Codegen {
        detail: err.to_string(),
    })?;

    let code = code.to_string();

    let mut out = String::with_capacity(HEADER.len() + code.len() + 64);
    out.push_str(HEADER);
    let _ = writeln!(out, "// {SCHEMA_MARKER} {:016x}", schema_digest(root)?);
    let _ = writeln!(out);
    out.push_str(&code);

    Ok(out)
}

/// Formats generated code so that it stays diffable.
///
/// `xsd-parser` delivers a `TokenStream` in one line. If rustfmt fails, the
/// unformatted code is used — the codegen shall not fail on cosmetics.
pub(crate) fn format(code: &str, root: &Path) -> String {
    use std::io::Write as _;
    use std::process::{Command, Stdio};

    let child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout", "--quiet"])
        .current_dir(root)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn();

    let Ok(mut child) = child else {
        return code.to_owned();
    };

    if let Some(mut stdin) = child.stdin.take()
        && stdin.write_all(code.as_bytes()).is_err()
    {
        return code.to_owned();
    }

    match child.wait_with_output() {
        Ok(out) if out.status.success() => {
            String::from_utf8(out.stdout).unwrap_or_else(|_| code.to_owned())
        }
        _ => code.to_owned(),
    }
}

/// Regenerates `crates/tg-defs/src/generated.rs` from the XSD.
pub(crate) fn run(root: &Path, check_only: bool) -> Result<(), TaskError> {
    let target: PathBuf = root.join(TARGET);
    let generated = format(&render(root)?, root);

    if check_only {
        let current = fs::read_to_string(&target)?;
        if current == generated {
            eprintln!("codegen: {TARGET} is up to date.");
            return Ok(());
        }
        return Err(TaskError::CodegenDrift);
    }

    fs::write(&target, generated)?;
    eprintln!("codegen: {TARGET} produced from {SCHEMA}.");

    Ok(())
}
