//! Protobuf codegen driver for the SPIFFE Workload API (ADR-0035).
//!
//! Produces the server stub in `crates/tg-identity/src/workload_api/pb.rs` from
//! `third-party/spiffe-workload-api/workload.proto`.
//!
//! The result is **checked in**, for the same reasons as with the XSD codegen
//! (see [`crate::codegen`]) — plus a third: **no `protoc`**. The compiler is
//! [`protox`], pure Rust. Exactly that was the objection ADR-0035 hung on:
//! protobuf demands a second toolchain. It does not.
//!
//! **Both sides** are produced, and the reason for the client is a test reason,
//! not a production one: the sidecar from phase 8 uses the `spiffe` crate,
//! because only a foreign client substantiates the interop. Two refusal cases a
//! foreign client cannot trigger at all — it always sets the prescribed header,
//! and it does not call the JWT methods.

use std::fs;
use std::path::{Path, PathBuf};

use crate::TaskError;

const PROTO: &str = "third-party/spiffe-workload-api/workload.proto";
const INCLUDE: &str = "third-party/spiffe-workload-api";
const TARGET: &str = "crates/tg-identity/src/workload_api/pb.rs";

/// Header of the product.
///
/// The lint exceptions deliberately apply only to this module: generated code
/// does not satisfy `missing_docs` and `clippy::pedantic` and shall not.
/// `unsafe` stays forbidden via the crate root (invariant 2 from CLAUDE.md).
const HEADER: &str = "\
// @generated by `cargo xtask proto` from third-party/spiffe-workload-api/workload.proto
// — do not edit by hand.
//
// Regenerate:  cargo xtask proto
// Check:       cargo xtask proto --check
//
// ADR-0035. The `.proto` is the unmodified version of the SPIFFE specification;
// for provenance and reason see
// third-party/spiffe-workload-api/PROVENANCE.md.
//
// Both sides are produced. The client is pure test need: it triggers the two
// refusal cases a well-behaved foreign client cannot trigger (missing header,
// JWT methods).

#![allow(missing_docs, unreachable_pub, clippy::all, clippy::pedantic)]

";

/// How the version line in the product's header begins.
///
/// The same construction as with the XSD (`codegen.rs`), and for the same
/// reason: the stronger check (`proto --check`) runs in `cargo xtask ci` and not
/// in the Definition of Done. A test in `tg-identity` recomputes the number.
const PROTO_MARKER: &str = "Proto version:";

/// The `.proto`'s version, as a number over its bytes.
///
/// FNV-1a written out, not `DefaultHasher` (ADR-0057: that one's result is not
/// stable between Rust versions). It has to achieve nothing cryptographically:
/// the `.proto` is vendored and its provenance substantiated in
/// `PROVENANCE.md` — the question here is only whether somebody changed it
/// without regenerating.
fn proto_digest(root: &Path) -> Result<u64, TaskError> {
    let proto = fs::read(root.join(PROTO))?;

    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in &proto {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }

    Ok(hash)
}

/// Regenerates the server stub from the `.proto`.
pub(crate) fn run(root: &Path, check_only: bool) -> Result<(), TaskError> {
    let target: PathBuf = root.join(TARGET);
    let generated = crate::codegen::format(&render(root)?, root);

    if check_only {
        let current = fs::read_to_string(&target)?;
        if current == generated {
            eprintln!("proto: {TARGET} is up to date.");
            return Ok(());
        }
        return Err(TaskError::ProtoDrift);
    }

    fs::write(&target, generated)?;
    eprintln!("proto: {TARGET} produced from {PROTO}.");

    Ok(())
}

fn render(root: &Path) -> Result<String, TaskError> {
    // `protox` reads and compiles the `.proto` into a FileDescriptorSet — what
    // `protoc` otherwise delivers. The include path points at the vendored
    // directory so that the import of google/protobuf/struct.proto is resolved
    // there and not in a system installation.
    let descriptors = protox::compile([root.join(PROTO)], [root.join(INCLUDE)]).map_err(|err| {
        TaskError::Proto {
            detail: err.to_string(),
        }
    })?;

    let out = tempdir(root)?;
    tonic_prost_build::configure()
        .build_server(true)
        .build_client(true)
        .out_dir(&out)
        .compile_fds(descriptors)
        .map_err(|err| TaskError::Proto {
            detail: err.to_string(),
        })?;

    // `workload.proto` has no `package`, so the product is called `_.rs`.
    let body = fs::read_to_string(out.join("_.rs"))?;
    fs::remove_dir_all(&out)?;

    Ok(format!(
        "{HEADER}// {PROTO_MARKER} {:016x}\n\n{body}",
        proto_digest(root)?
    ))
}

fn tempdir(root: &Path) -> Result<PathBuf, TaskError> {
    let dir = root.join("target").join("xtask-proto");
    if dir.exists() {
        fs::remove_dir_all(&dir)?;
    }
    fs::create_dir_all(&dir)?;

    Ok(dir)
}
